config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'currency#index'

  resource :currency, only:[:create, :show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
# frozen_string_literal: true

class Currency < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/currency_controller.rb
# frozen_string_literal: true

class CurrencyController < ApplicationController
  def index
    @currencies = Currency.all
  end

  def create
    @currency = GetCurrencyValue.call(currency_params)
  end

  def show
    flash[:notice] = "Passou por aqui!"
  end

  private

  def currency_params
    params.require(:currency).permit(:value, :origin_id, :destiny_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/currency_converter_helper.rb
# frozen_string_literal: true

module CurrencyConverterHelper
end

app/views/currency/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"/>
    <%= javascript_include_tag 'script.js' %>
    <title>Conversor de Moedas</title>
  </head>
  <body>
      <form action="" name="CurrencyConverter" method="get">
        <span class="box box1">
          <div class="nested">
            <strong>Insira o valor a converter:</strong>
            <div class="tooltip">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" id="IconChangeColor" height="15" width="15"><rect width="256" height="256" fill="none"></rect><circle cx="128" cy="128" r="96" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></circle><polyline points="120 120 128 120 128 176 136 176" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></polyline><circle cx="126" cy="84" r="10"></circle></svg>
              <span class="tooltiptext">Adicione o valor em moeda para converter</span>
            </div>
          </div>
          <div class="nested">
            <input inputmode="numeric" placeholder="0,00" id="input_value" name="value_to_convert" onKeyUp="mascaraMoeda(this, event)">
          </div>
        </span>

        <span class="box2">
          <div class="nested">
            <strong>Escolha a moeda de origem</strong>
            <div class="tooltip">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" id="IconChangeColor" height="15" width="15"><rect width="256" height="256" fill="none"></rect><circle cx="128" cy="128" r="96" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></circle><polyline points="120 120 128 120 128 176 136 176" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></polyline><circle cx="126" cy="84" r="10"></circle></svg>
              <span class="tooltiptext">Selecione a moeda que será a base para conversão. Este valor será transformado na próxima moeda.</span>
            </div>
          </div>
          <div class="nested">
            <select name="select">
              <% @currencies.each_with_index do |currency, index| %>
                <option value=currency_initial1><%= currency.country %> <strong><%= currency.name%></strong> (<%= currency.initials %>)</option>
              <% end %>
            </select>
          </div>
        </span>
        
        <span class="box3">
          <div>
            <strong>Escolha a moeda de destino</strong>
            <div class="tooltip">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" id="IconChangeColor" height="15" width="15"><rect width="256" height="256" fill="none"></rect><circle cx="128" cy="128" r="96" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></circle><polyline points="120 120 128 120 128 176 136 176" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></polyline><circle cx="126" cy="84" r="10"></circle></svg>
              <span class="tooltiptext">Selecione a moeda do reultado da conversão. Este valor será o correspondente à primeira moeda</span>
            </div>
          </div>
          <div>
            <select name="select">
              <% @currencies.each_with_index do |currency, index| %>
                <option value=currency_initial2><%= currency.country %> <strong><%= currency.name%></strong> (<%= currency.initials %>)</option>
              <% end %>
            </select>
          </div>
        </span>
        <p>

        <div class="box4">
          <button type="submit" value="convert"> <%= link_to "Converter",currency_path, class:"button" %></button>
        </div>
      </form>
      <div class="box5">
          <output type="number" class="output" name="value_from_convert" value="value_from_convert" disabled>
      </div>   
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conversor de Moedas - Projeto Mentoriar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
     <nav><h1> Conversor de Moedas </h1></nav>
    </header>
    <div class="content">
      <%= yield %>
    </div>

    <footer>
      <p>
        Copyright &copy; <%= Time.now.year %>
        <a href='https://github.com/mnquintino' target='_blank'>Manara GitHub</a>
      </p>
    </footer>
  </body>
</html>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>